apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: odoo
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "6Gi"
            cpu: "3000m"
