apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: odoo-dev

bases:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: development

replicas:
  - name: odoo
    count: 1

patchesStrategicMerge:
  - replica-patch.yaml
  - resource-patch.yaml

images:
  - name: harbor.example.com/odoo/odoo
    newTag: dev-latest
